# Change these first
owner: Thanawatttt # Your GitHub organization or username, where this repository lives
repo: meouptime # The name of this repository

sites:
  - name: BPK-1
    url: bpk1.meo.pp.ua
    port: 22
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.meo.pp.ua
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: meostatus
  theme: ocean
  introTitle: ""
  introMessage: status page
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
